#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-lsp-server
Version  : 1.3.3
Release  : 8
URL      : https://files.pythonhosted.org/packages/7a/67/5789a8280ffa9e29c38e1456effa4af9e3d85058c9aba93a2c4222f52557/python-lsp-server-1.3.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/7a/67/5789a8280ffa9e29c38e1456effa4af9e3d85058c9aba93a2c4222f52557/python-lsp-server-1.3.3.tar.gz
Summary  : Python Language Server for the Language Server Protocol
Group    : Development/Tools
License  : MIT
Requires: python-lsp-server-bin = %{version}-%{release}
Requires: python-lsp-server-license = %{version}-%{release}
Requires: python-lsp-server-python = %{version}-%{release}
Requires: python-lsp-server-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(jedi)
BuildRequires : pypi(pluggy)
BuildRequires : pypi(python_lsp_jsonrpc)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(ujson)

%description
# Python LSP Server
[![image](https://github.com/python-ls/python-ls/workflows/Linux%20tests/badge.svg)](https://github.com/python-ls/python-ls/actions?query=workflow%3A%22Linux+tests%22) [![image](https://github.com/python-ls/python-ls/workflows/Mac%20tests/badge.svg)](https://github.com/python-ls/python-ls/actions?query=workflow%3A%22Mac+tests%22) [![image](https://github.com/python-ls/python-ls/workflows/Windows%20tests/badge.svg)](https://github.com/python-ls/python-ls/actions?query=workflow%3A%22Windows+tests%22) [![image](https://img.shields.io/github/license/python-ls/python-ls.svg)](https://github.com/python-ls/python-ls/blob/master/LICENSE)

%package bin
Summary: bin components for the python-lsp-server package.
Group: Binaries
Requires: python-lsp-server-license = %{version}-%{release}

%description bin
bin components for the python-lsp-server package.


%package license
Summary: license components for the python-lsp-server package.
Group: Default

%description license
license components for the python-lsp-server package.


%package python
Summary: python components for the python-lsp-server package.
Group: Default
Requires: python-lsp-server-python3 = %{version}-%{release}

%description python
python components for the python-lsp-server package.


%package python3
Summary: python3 components for the python-lsp-server package.
Group: Default
Requires: python3-core
Provides: pypi(python_lsp_server)
Requires: pypi(jedi)
Requires: pypi(pluggy)
Requires: pypi(python_lsp_jsonrpc)
Requires: pypi(setuptools)
Requires: pypi(ujson)

%description python3
python3 components for the python-lsp-server package.


%prep
%setup -q -n python-lsp-server-1.3.3
cd %{_builddir}/python-lsp-server-1.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639421324
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-lsp-server
cp %{_builddir}/python-lsp-server-1.3.3/LICENSE %{buildroot}/usr/share/package-licenses/python-lsp-server/c0a4218ed5c81a62f45a9cc14735457e71102cee
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pylsp

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-lsp-server/c0a4218ed5c81a62f45a9cc14735457e71102cee

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
